# Site information
title: David's Blog
email: david.federman@outlook.com
description: Some guy's programming blog.
baseurl: ""
url: "https://dfederm.com/"
github_username:  dfederm

# Site settings
permalink: /:title
markdown: kramdown
theme: minima # Supported themes: https://pages.github.com/themes/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
