# Site information
title: Maher's Blog
email: m.maher@infinitytech.ltd
description: Some guy's programming blog.
baseurl: ""
url: "https://maher.github.io"

# Site settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

disqus:
  shortname: maher

google_analytics: UA-158306797-1
google_ads: ca-pub-7807152857287265

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
